---
- name: Create download dir for k9s
  file:
    path: "{{ k9s_download_dir }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0755

- name: Download and unarchive arm64 k9s
  unarchive:
    src: "{{ k9s_download_base_url }}/{{ k9s_version }}/k9s_Linux_arm64.tar.gz"
    remote_src: yes
    dest: "{{ k9s_download_dir }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0755
  when: ansible_architecture == "aarch64"

- name: Download and unarchive x86_64 k9s
  unarchive:
    src: "{{ k9s_download_base_url }}/{{ k9s_version }}/k9s_Linux_x86_64.tar.gz"
    remote_src: yes
    dest: "{{ k9s_download_dir }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0755
  when: ansible_architecture == "x86_64"

- name: Copy k9s binary to /usr/local/bin
  copy:
    src: "{{ k9s_download_dir }}/k9s"
    remote_src: yes
    dest: /usr/local/bin/k9s
    owner: root
    group: root
    mode: 0755
