---
- name: Copy main.tf file
  template:
    src: templates/main.tf
    dest: "{{ terraform_files_dir }}/main.tf"
    owner: root
    group: root
    mode: 0644
  register: main
  when: inventory_hostname in groups["rancher"]

- name: Copy variables.tf file
  template:
    src: templates/variables.tf
    dest: "{{ terraform_files_dir }}/variables.tf"
    owner: root
    group: root
    mode: 0644
  register: variables
  when: inventory_hostname in groups["rancher"]

- name: Copy terraform.tfvars file
  template:
    src: templates/terraform.tfvars
    dest: "{{ terraform_files_dir }}/terraform.tfvars"
    owner: root
    group: root
    mode: 0600
  register: tfvars
  when: inventory_hostname in groups["rancher"]

- name: Create k8s namespace fleet-ns
  kubernetes.core.k8s:
    kubeconfig: "{{ rancher_k3s_kubeconfig }}"
    name: fleet-ns
    api_version: v1
    kind: Namespace
    state: present
  when: inventory_hostname in groups["rancher"]

- name: Register initial RKE2 cluster into Rancher
  terraform:
    project_path: "{{ terraform_files_dir }}"
    state: present
    force_init: yes
  register: tf_output
  when: inventory_hostname in groups["rancher"]

- name: Print tf_output
  debug:
    msg: "{{ tf_output.outputs.cluster_registration_token.value[0].node_command[1:] }}"
  when: inventory_hostname in groups["rancher"]

- name: Set node command fact for k8s nodes
  set_fact: node_command="{{ tf_output.outputs.cluster_registration_token.value[0].node_command[1:] }}"
  delegate_to: "{{ item }}"
  delegate_facts: True
  with_items: "{{ groups['k8s'] }}"
  when: inventory_hostname in groups["rancher"]

- name: Run node command for master nodes
  shell: |
    {{ node_command }} --etcd --controlplane
  when: inventory_hostname in groups["k8s_master"]

- name: Run node command for worker nodes
  shell: |
    {{ node_command }} --worker
  when: inventory_hostname in groups["k8s_worker"]
