master:
  hosts:
    master100:
    master101:
    master102:

control_plane:
  children:
    master:

worker:
  hosts:
    worker103:
    worker104:
    worker105:

kubernetes:
  children:
    master:
    worker:

rancher:
  hosts:
    racoonpi:
