rancher:
  hosts:
    racoonpi:

k8s_master:
  hosts:
    master100:
    master101:
    master102:

k8s_control_plane:
  children:
    master:

k8s_worker:
  hosts:
    worker103:
    worker104:
    worker105:

k8s:
  children:
    master:
    worker:
