---
- name: Enable cgroup via boot commandline if not already enabled for Ubuntu on a Raspberry Pi
  lineinfile:
    path: /boot/firmware/cmdline.txt
    backrefs: yes
    regexp: '^((?!.*\bcgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory\b).*)$'
    line: '\1 cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory'
  notify: reboot

- meta: flush_handlers

- name: Run Rancher container
  docker_container:
    name: rancher
    image: rancher/rancher:{{ rancher_version }}
    state: started
    privileged: yes
    detach: yes
    restart_policy: unless-stopped
    published_ports:
      - 80:80
      - 443:443
    env:
      CATTLE_BOOTSTRAP_PASSWORD={{ rancher_bootstrap_password }}
      DOCKER_CLIENT_TIMEOUT=120
