---
- name: Remove old versions
  apt:
    name:
      - docker
      - docker-engine
      - docker.io
      - containerd
      - runc
    state: absent

- name: Install prerequisites
  apt:
    name:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: present
    update_cache: yes

- name: Get architecture
  shell:
    dpkg --print-architecture
  register: architecture

- name: Check if Docker GPG key exists on host
  stat:
    path: "{{ docker_gpg_key }}"
  register: key

- name: Add Docker GPG key
  shell:
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o {{ docker_gpg_key }}
  when: key.stat.exists == False

- name: Add Docker APT repository
  copy:
    content: |
      deb [arch={{ architecture.stdout }} signed-by={{ docker_gpg_key }}] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
    dest: /etc/apt/sources.list.d/docker.list
    mode: 0644
    owner: root
    group: root

- name: Install Docker Engine
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose
      - docker-compose-plugin
      - python3-docker
    state: present
    update_cache: yes
  notify:
    - reload systemd
    - restart docker

- name: Add user to Docker group
  user:
    name: "{{ docker_user }}"
    groups: docker
    append: yes

- meta: flush_handlers
